### ISSUE TITLE
Capture keyboard volume changes

### ISSUE THREAD

**Issue by Yelles** [rlxone/MultiSoundChanger#3]
Hi,

Thanks for your work, it's very useful ! 

Do you plan to capture system volume changes (from keyboard for example) ?

**Comment by rlxone** [comment]
Hi,

Thanks you!

I will add your suggestion to feature request list and implement in free time.

**Comment by thingsapart** [comment]
#4 added a pull request to support media keys.

This requires giving the app "Accessibility" permissions in "System Preferences"/"Security & Privacy"/"Privacy Tab"/"Accessibility" to intercept keyboard events.

I pushed a binary to a fork of this repo: https://github.com/thingsapart/MultiSoundChanger/releases/tag/0.1
